TRUNCATE TABLE OPERATION CASCADE;
TRUNCATE TABLE PERSON_COMPTE CASCADE;
TRUNCATE TABLE AUTHORITY CASCADE;
TRUNCATE TABLE PERSON CASCADE;
TRUNCATE TABLE COMPTE CASCADE;

ALTER SEQUENCE COMPTE_ID_SEQ MINVALUE 1 RESTART WITH 1;
ALTER SEQUENCE OPERATION_ID_SEQ MINVALUE 1 RESTART WITH 1;
ALTER SEQUENCE PERSON_ID_SEQ MINVALUE 1 RESTART WITH 1;

